site_name: TON.DEV Docs

nav: 
    - Compilers:
   
        - 'Installation': 'Compilers/Installation.md'
        - 'Linker CLI': 'Compilers/Linker CLI.md'
        - Solidity Compiler:
            - 'Feature Support': 'Compilers/Solidity Compiler/Solidity Support Status.md'
            - 'Using the compiler': 'Compilers/Solidity Compiler/Usage.md'
           
        - LLVM Compiler:
            - 'C Support Status': 'Compilers/LLVM Compiler/C Support Status.md' 
            - 'Debugging Options': 'Compilers/LLVM Compiler/Debugging Options.md'
            - 'Compiling C': 'Compilers/LLVM Compiler/Compiling and Deploying C Contracts.md' 
   

    - SDK:
        - 'Overview': 'SDK/Overview.md'
        - 'Installation': 'SDK/Installation.md'
        - 'Local Node': 'SDK/Local Node.md'
        - 'TONDEV CLI': 'SDK/TONDEV CLI.md'
        - Using Client Libraries:
            - 'Library Modules': 'SDK/Client Libraries/Library Modules.md'
            - 'Rust': 'SDK/Client Libraries/Using Libraries/Rust.md'
            - 'JavaScript': 'SDK/Client Libraries/Using Libraries/Node.js.md'
        - SDK API:
            - 'Contract Management': 'SDK/SDK API/Contract Management.md'
        
        
        - Misc:
            - 'Getting Logs': 'SDK/Auxiliaries/Getting Logs.md'
            - 'Troubleshooting': 'SDK/Auxiliaries/Troubleshooting.md'
            - 'Installing Ubuntu VM': 'SDK/Auxiliaries/Installing Ubuntu VM.md'
    
    - Developing Contracts:
        - 'ABI Specification V1': 'Smart Contract Lore/ABI Specification New.md'
        - 'ABI Specification V0': 'Smart Contract Lore/ABI Specification.md'
        - 'Key Generation and Use': 'Smart Contract Lore/Key Generation and Use.md'
        - 'Deploying contract from contract': 'Smart Contract Lore/Deploying contract from contract.md'
        - 'Modifying Contracts': 'Smart Contract Lore/TVM_setcode.md'
        - 'Managing Gas': 'Smart Contract Lore/TVM_accept.md'
        
    - Gas Specs:
        - 'Gas Calculation and Storage': Gas Specs/Gas Calculation Basics.md'
        - 'Transaction Fee Calculation': 'Gas Specs/Transaction Fee Calculation.md'
    - TON:
        - 'TVM Error Codes': 'TON Blockchain/TVM Error Codes.md'
        - 'TON Whitepaper': 'TON Blockchain/TON Specifications/TON Whitepaper.md'
        - 'TON Virtual Machine': 'TON Blockchain/TON Specifications/TON Virtual Machine.md'
        - 'TON Blockchain': 'TON Blockchain/TON Specifications/TON Blockchain.md'
        - 'Lite Client Guide': 'TON Blockchain/TON Specifications/Lite Client Guide.md'
        

    - FAQ:
       - 'Solidity Compiler': 'FAQ/Solidity Compiler.md' 
       - 'Smart Contracts': 'FAQ/Smart Contracts.md' 
       - 'TON and TVM': 'FAQ/TON and TVM.md'    
       - 'SDK and Integration': 'FAQ/SDK and Integration.md'
       - 'Glossary': 'Glossary.md' 
    - Changelog:
        - 'Archive 2019': 'Release Notes Archive.md'

theme:
    name: mkdocs
    custom_dir: custom_dir/

    
